channels:
  - conda-forge

name: PDS-Pipelines
dependencies:
    - python=3
    - psycopg2
    - lxml
    - pytz
    - sqlalchemy
    - geoalchemy2
    - pvl
    - pysis
    - redis
    - pip
    - pytest
    - pytest-cov
    - jinja2
    - mock
    - shapely
    - sqlalchemy-utils
    - gdal
    - pip:
        - redis>=2.0.0,<3.0.0
